# Generated by Django 3.0.5 on 2020-10-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campname', models.CharField(max_length=100)),
                ('campadd', models.CharField(max_length=200)),
                ('campdate', models.CharField(max_length=100)),
                ('camptime', models.CharField(max_length=100)),
                ('regcontact', models.CharField(max_length=100)),
            ],
        ),
    ]
